version: "3"

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181"
    hostname: zookeeper
  kafka:
    image: wurstmeister/kafka
    command: [start-kafka.sh]
    ports:
      - "9092:9092"
    hostname: kafka
    environment:
#      KAFKA_CREATE_TOPICS: "mc1-mc2_1:1:1,mc2-mc3_1:1:1,mc3-mc1_1:1:1" # topic:partition:replicas
      KAFKA_ADVERTISED_HOST_NAME: kafka # docker-machine ip
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_PORT: 9092
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - "zookeeper"
  redis:
    image: redis
    ports:
      - "6379:6379"
  web:
    build:
      context: ./mc1
    restart: always
    command: python3 /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./mc1:/code/
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      SECRET_KEY: bigsecretkey
      DJANGO_CONFIGURATION: Develop
      DJANGO_SETTINGS_MODULE:
  web1:
    build:
      context: ./mc2
    restart: always
    command: python3 /code/manage.py runserver 0.0.0.0:8001
    volumes:
      - ./mc2:/code/
    ports:
      - "8001:8001"
    depends_on:
      - redis
    environment:
      SECRET_KEY: bigsecretkey
      DJANGO_CONFIGURATION: Develop
      DJANGO_SETTINGS_MODULE:
  web2:
    build:
      context: ./mc3
    restart: always
    command: python3 /code/manage.py runserver 0.0.0.0:8002
    volumes:
      - ./mc3:/code/
    ports:
      - "8002:8002"
    depends_on:
      - redis
    environment:
      SECRET_KEY: bigsecretkey
      DJANGO_CONFIGURATION: Develop
      DJANGO_SETTINGS_MODULE:
  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "8080:8080"
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
      - KAFKA_CLUSTERS_0_READONLY=false
volumes:
  pgdata:
