version: "3"

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  web:
    build:
      context: ./mc1
    restart: always
    command: python3 /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./mc1:/code/
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      SECRET_KEY: bigsecretkey
      DJANGO_CONFIGURATION: Develop
      DJANGO_SETTINGS_MODULE:
  web1:
    build:
      context: ./mc2
    restart: always
    command: python3 /code/manage.py runserver 0.0.0.0:8001
    volumes:
      - ./mc2:/code/
    ports:
      - "8001:8001"
    depends_on:
      - redis
    environment:
      SECRET_KEY: bigsecretkey
      DJANGO_CONFIGURATION: Develop
      DJANGO_SETTINGS_MODULE:
  web2:
    build:
      context: ./mc3
    restart: always
    command: python3 /code/manage.py runserver 0.0.0.0:8002
    volumes:
      - ./mc3:/code/
    ports:
      - "8002:8002"
    depends_on:
      - redis
    environment:
      SECRET_KEY: bigsecretkey
      DJANGO_CONFIGURATION: Develop
      DJANGO_SETTINGS_MODULE:
volumes:
  pgdata:
