# Generated by Django 3.2.2 on 2021-08-14 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.IntegerField(default=0)),
                ('MC1_timestamp', models.DateTimeField(auto_now_add=True)),
                ('MC2_timestamp', models.DateTimeField(blank=True, null=True)),
                ('MC3_timestamp', models.DateTimeField(blank=True, null=True)),
                ('end_timestamp', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'messages',
            },
        ),
    ]
